const { HashMap } = require("./hashmap.js");

console.clear()


//#region beginning
const test = new HashMap()
test.set("Alice_0", "likes pizza");
test.set("Bob_1", "plays guitar");
test.set("Charlie_2", "writes code");
test.set("Diana_3", "enjoys hiking");
test.set("Ethan_4", "loves dogs");
test.set("Fiona_5", "reads books");
test.set("George_6", "drinks coffee");
test.set("Hannah_7", "rides a bike");
test.set("Ian_8", "skates");
test.set("Jasmine_9", "collects stamps");
test.set("Kyle_10", "builds PCs");
test.set("Luna_11", "paints");
test.set("Mike_12", "bakes cakes");
test.set("Nina_13", "watches anime");
test.set("Oscar_14", "travels often");
test.set("Paula_15", "sings");
test.set("Quinn_16", "does yoga");
test.set("Rachel_17", "volunteers");
test.set("Steve_18", "runs marathons");
test.set("Tina_19", "does standup");
test.set("Uma_20", "plays chess");
test.set("Victor_21", "gardens");
test.set("Wendy_22", "photographs birds");
test.set("Xavier_23", "plays violin");
test.set("Yara_24", "is a gamer");
test.set("Zane_25", "likes pizza");
test.set("Alice_26", "plays guitar");
test.set("Bob_27", "writes code");
test.set("Charlie_28", "enjoys hiking");
test.set("Diana_29", "loves dogs");
test.set("Ethan_30", "reads books");
test.set("Fiona_31", "drinks coffee");
test.set("George_32", "rides a bike");
test.set("Hannah_33", "skates");
test.set("Ian_34", "collects stamps");
test.set("Jasmine_35", "builds PCs");
test.set("Kyle_36", "paints");
test.set("Luna_37", "bakes cakes");
test.set("Mike_38", "watches anime");
test.set("Nina_39", "travels often");
test.set("Oscar_40", "sings");
test.set("Paula_41", "does yoga");
test.set("Quinn_42", "volunteers");
test.set("Rachel_43", "runs marathons");
test.set("Steve_44", "does standup");
test.set("Tina_45", "plays chess");
test.set("Uma_46", "gardens");
test.set("Victor_47", "photographs birds");
test.set("Wendy_48", "plays violin");
test.set("Xavier_49", "is a gamer");
test.set("Yara_50", "likes pizza");
test.set("Zane_51", "plays guitar");
test.set("Alice_52", "writes code");
test.set("Bob_53", "enjoys hiking");
test.set("Charlie_54", "loves dogs");
test.set("Diana_55", "reads books");
test.set("Ethan_56", "drinks coffee");
test.set("Fiona_57", "rides a bike");
test.set("George_58", "skates");
test.set("Hannah_59", "collects stamps");
test.set("Ian_60", "builds PCs");
test.set("Jasmine_61", "paints");
test.set("Kyle_62", "bakes cakes");
test.set("Luna_63", "watches anime");
test.set("Mike_64", "travels often");
test.set("Nina_65", "sings");
test.set("Oscar_66", "does yoga");
test.set("Paula_67", "volunteers");
test.set("Quinn_68", "runs marathons");
test.set("Rachel_69", "does standup");
test.set("Steve_70", "plays chess");
test.set("Tina_71", "gardens");
test.set("Uma_72", "photographs birds");
test.set("Victor_73", "plays violin");
test.set("Wendy_74", "is a gamer");
test.set("Xavier_75", "likes pizza");
test.set("Yara_76", "plays guitar");
test.set("Zane_77", "writes code");
test.set("Alice_78", "enjoys hiking");
test.set("Bob_79", "loves dogs");
test.set("Charlie_80", "reads books");
test.set("Diana_81", "drinks coffee");
test.set("Ethan_82", "rides a bike");
test.set("Fiona_83", "skates");
test.set("George_84", "collects stamps");
test.set("Hannah_85", "builds PCs");
test.set("Ian_86", "paints");
test.set("Jasmine_87", "bakes cakes");
test.set("Kyle_88", "watches anime");
test.set("Luna_89", "travels often");
test.set("Mike_90", "sings");
test.set("Nina_91", "does yoga");
test.set("Oscar_92", "volunteers");
test.set("Paula_93", "runs marathons");
test.set("Quinn_94", "does standup");
test.set("Rachel_95", "plays chess");
test.set("Steve_96", "gardens");
test.set("Tina_97", "photographs birds");
test.set("Uma_98", "plays violin");
test.set("Victor_99", "is a gamer");
test.set("Wendy_100", "likes pizza");
test.set("Xavier_101", "plays guitar");
test.set("Yara_102", "writes code");
test.set("Zane_103", "enjoys hiking");
test.set("Alice_104", "loves dogs");
test.set("Bob_105", "reads books");
test.set("Charlie_106", "drinks coffee");
test.set("Diana_107", "rides a bike");
test.set("Ethan_108", "skates");
test.set("Fiona_109", "collects stamps");
test.set("George_110", "builds PCs");
test.set("Hannah_111", "paints");
test.set("Ian_112", "bakes cakes");
test.set("Jasmine_113", "watches anime");
test.set("Kyle_114", "travels often");
test.set("Luna_115", "sings");
test.set("Mike_116", "does yoga");
test.set("Nina_117", "volunteers");
test.set("Oscar_118", "runs marathons");
test.set("Paula_119", "does standup");
test.set("Quinn_120", "plays chess");
test.set("Rachel_121", "gardens");
test.set("Steve_122", "photographs birds");
test.set("Tina_123", "plays violin");
test.set("Uma_124", "is a gamer");
test.set("Victor_125", "likes pizza");
test.set("Wendy_126", "plays guitar");
test.set("Xavier_127", "writes code");
test.set("Yara_128", "enjoys hiking");
test.set("Zane_129", "loves dogs");
test.set("Alice_130", "reads books");
test.set("Bob_131", "drinks coffee");
test.set("Charlie_132", "rides a bike");
test.set("Diana_133", "skates");
test.set("Ethan_134", "collects stamps");
test.set("Fiona_135", "builds PCs");
test.set("George_136", "paints");
test.set("Hannah_137", "bakes cakes");
test.set("Ian_138", "watches anime");
test.set("Jasmine_139", "travels often");
test.set("Kyle_140", "sings");
test.set("Luna_141", "does yoga");
test.set("Mike_142", "volunteers");
test.set("Nina_143", "runs marathons");
test.set("Oscar_144", "does standup");
test.set("Paula_145", "plays chess");
test.set("Quinn_146", "gardens");
test.set("Rachel_147", "photographs birds");
test.set("Steve_148", "plays violin");
test.set("Tina_149", "is a gamer");
test.set("Uma_150", "likes pizza");
test.set("Victor_151", "plays guitar");
test.set("Wendy_152", "writes code");
test.set("Xavier_153", "enjoys hiking");
test.set("Yara_154", "loves dogs");
test.set("Zane_155", "reads books");
test.set("Alice_156", "drinks coffee");
test.set("Bob_157", "rides a bike");
test.set("Charlie_158", "skates");
test.set("Diana_159", "collects stamps");
test.set("Ethan_160", "builds PCs");
test.set("Fiona_161", "paints");
test.set("George_162", "bakes cakes");
test.set("Hannah_163", "watches anime");
test.set("Ian_164", "travels often");
test.set("Jasmine_165", "sings");
test.set("Kyle_166", "does yoga");
test.set("Luna_167", "volunteers");
test.set("Mike_168", "runs marathons");
test.set("Nina_169", "does standup");
test.set("Oscar_170", "plays chess");
test.set("Paula_171", "gardens");
test.set("Quinn_172", "photographs birds");
test.set("Rachel_173", "plays violin");
test.set("Steve_174", "is a gamer");
test.set("Tina_175", "likes pizza");
test.set("Uma_176", "plays guitar");
test.set("Victor_177", "writes code");
test.set("Wendy_178", "enjoys hiking");
test.set("Xavier_179", "loves dogs");
test.set("Yara_180", "reads books");
test.set("Zane_181", "drinks coffee");
test.set("Alice_182", "rides a bike");
test.set("Bob_183", "skates");
test.set("Charlie_184", "collects stamps");
test.set("Diana_185", "builds PCs");
test.set("Ethan_186", "paints");
test.set("Fiona_187", "bakes cakes");
test.set("George_188", "watches anime");
test.set("Hannah_189", "travels often");
test.set("Ian_190", "sings");
test.set("Jasmine_191", "does yoga");
test.set("Kyle_192", "volunteers");
test.set("Luna_193", "runs marathons");
test.set("Mike_194", "does standup");
test.set("Nina_195", "plays chess");
test.set("Oscar_196", "gardens");
test.set("Paula_197", "photographs birds");
test.set("Quinn_198", "plays violin");
test.set("Rachel_199", "is a gamer");
//#endregion



console.log("---- DEMO START ----");
console.log("Get Alice_0:", test.get("Alice_0"));
console.log("Has Luna_11:", test.has("Luna_11"));
console.log("Remove Ethan_30:", test.remove("Ethan_30"));
console.log("Has Ethan_30 after removal:", test.has("Ethan_30"));
// console.log("All keys:", test.keys());
// console.log("All values:", test.values());
// console.log("All entries:", test.entries());
test.clear();

console.log("Entries after clear:", test.entries());
console.log("---- DEMO END ----");
